import RPi.GPIO as GPIO
from time import sleep

GPIO.setmode(GPIO.BCM)

Col1 = 19
Col2 = 7
Col3 = 1
Col4 = 6
Col5 = 16

Row1 = 26
Row2 = 21
Row3 = 13
Row4 = 25
Row5 = 20
Row6 = 8
Row7 = 12

rows = [Row1, Row2, Row3, Row4, Row5, Row6, Row7]
columns = [Col1, Col2, Col3, Col4, Col5]


def clean():
    GPIO.cleanup()


def setup_pin():
    GPIO.setup(rows, GPIO.OUT)
    GPIO.setup(columns, GPIO.OUT)


def leds_off():
    GPIO.output(columns, GPIO.LOW)
    GPIO.output(rows, GPIO.HIGH)


def show_a():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows[1:], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row5], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row5], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row5], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows[1:], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_e():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_i():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)


def show_o():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows[1:6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows[1:6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)


def show_u():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows[:-1], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows[:-1], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_b():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row2, Row3, Row5, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_c():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows[1:6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row2, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_d():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows[1:6], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_f():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row4], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row4], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row1, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(Row1, GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_g():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows[1:6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row5, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row5, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row2, Row5, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_h():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row4, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(Row4, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row4, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_j():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output([Row1, Row5, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows[:-1], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_k():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row4, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row3, Row5], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row2, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_l():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)


def show_m():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row2, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(Row3, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row2, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_n():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row2, Row3], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row4, Row5], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row6, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_n1():
    for i in range(10):
        GPIO.output(columns, GPIO.HIGH)
        GPIO.output(Row1, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows[3:], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row3, Row4], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row5, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows[3:], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_p():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row4], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row4], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row4], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row2, Row3], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_q():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows[1:6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row5, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row6, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows[1:6], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_r():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row4], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row5], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row2, Row3, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_s():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output([Row2, Row3, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row2, Row5, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_t():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(Row1, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row1, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row1, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(Row1, GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_v():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows[:-2], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row6, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row6, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows[:-2], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)


def show_w():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row5, Row6], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row7, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output(rows, GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_x():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output([Row1, Row2, Row6, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row3, Row5], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(Row4, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row3, Row5], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row1, Row2, Row6, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_y():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output([Row1, Row2], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output(Row3, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output(rows[4:], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output(Row3, GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row1, Row2], GPIO.LOW)
        sleep(0.01)
        leds_off()


def show_z():
    for i in range(10):
        GPIO.output(Col1, GPIO.HIGH)
        GPIO.output([Row1, Row6, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col2, GPIO.HIGH)
        GPIO.output([Row1, Row5, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col3, GPIO.HIGH)
        GPIO.output([Row1, Row4, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col4, GPIO.HIGH)
        GPIO.output([Row1, Row3, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()
        sleep(0.01)
        GPIO.output(Col5, GPIO.HIGH)
        GPIO.output([Row1, Row2, Row7], GPIO.LOW)
        sleep(0.01)
        leds_off()

setup_pin()